spring:
  datasource:
    url: jdbc:mysql://${HOST}:3306/${DATABASE}
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 587
    protocol: smtp

application:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000

server:
  servlet:
    context-path: /api/v1/

springdoc:
  default-produces-media-type: application/json